version: "3.8"

services:
  azconprice-backend:
    image: agilazizovf/azconprice
    container_name: azconprice-backend
    ports:
      - "7135:7135"
    env_file:
      - ./.env  # Bu sətr Docker Compose-a .env faylını oxumasını deyir
    volumes:
      - azconprice_files:/app/files
    restart: always

volumes:
  azconprice_files: