version: "3.8"

services:
  azconprice-backend:
    image: agilazizovf/azconprice
    container_name: azconprice-backend
    ports:
      - "7135:7135"
    environment:
      # Provide the full connection string here
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=ep-rough-dew-a2fcsmvv-pooler.eu-central-1.aws.neon.tech;Database=azconpriceprod;Username=neondb_owner;Password=npg_Q5FWuvGZPXq8;SSL Mode=Require;Trust Server Certificate=true"
    volumes:
      - azconprice_files:/app/files
    restart: always

volumes:
  azconprice_files: