name: CI/CD for .NET Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t agilazizovf/azconprice .
          docker push agilazizovf/azconprice

      - name: Deploy to Ubuntu Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull agilazizovf/azconprice
            docker stop azconprice || true
            docker rm azconprice || true
            docker run -d \
            --name azconprice \
            -v /home/ubuntu/azconprice/files:/home/ubuntu/azconprice/files \
            -p 7135:7135 \
            agilazizovf/azconprice
